dist: xenial
language: python
sudo: true
branches:
  only:
    - master

python:
  - 3.6
  - 3.7
  - 3.8

env:
  - PYSAL_PYPI=true  MPLBACKEND="pdf" NUMBA=false
  - PYSAL_PYPI=false MPLBACKEND="pdf" NUMBA=false
  - PYSAL_PYPI=true  MPLBACKEND="pdf" NUMBA=true
  - PYSAL_PYPI=false MPLBACKEND="pdf" NUMBA=true

matrix:
  allow_failures:
    - python: 3.6
      env: PYSAL_PYPI=false MPLBACKEND="pdf" NUMBA=false
    - python: 3.7
      env: PYSAL_PYPI=false MPLBACKEND="pdf" NUMBA=false
    - python: 3.8
      env: PYSAL_PYPI=false MPLBACKEND="pdf" NUMBA=false
    - python: 3.6
      env: PYSAL_PYPI=false MPLBACKEND="pdf" NUMBA=true
    - python: 3.7
      env: PYSAL_PYPI=false MPLBACKEND="pdf" NUMBA=true
    - python: 3.8
      env: PYSAL_PYPI=false MPLBACKEND="pdf" NUMBA=true


before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ./miniconda
  - export PATH=`pwd`/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda create -y -q -n test-env python=$TRAVIS_PYTHON_VERSION
  - source activate test-env

install:
  - conda install --yes pip
  - pip install -r requirements.txt
  - pip install -r requirements_tests.txt
  - if "$NUMBA"; then
        echo 'testing with numba' && conda install --yes -c conda-forge "numba>=0.50";
    else
        echo 'testing without numba';
    fi;
  - if "$PYSAL_PYPI"; then
        echo 'testing pypi libpysal' && pip install libpysal;
    else
        echo 'testing git libpysal';
        git clone https://github.com/pysal/libpysal.git;
        cd libpysal; pip install .; cd ../;
    fi;

script:
  - python setup.py sdist >/dev/null
  - python setup.py install
  - nosetests --verbose --with-coverage --cover-package=esda;

notifications:
    email:
        recipients:
            - levi.john.wolf+travis@gmail.com
            - sjsrey+travis@gmail.com
            - weikang9009@gmail.com
        on_success: change
        on_failure: change

after_success:
  - coveralls
