name: esda
channels:
  - conda-forge
dependencies:
  - python=3.12
  # required
  - libpysal
  - numpy
  - pandas
  - scikit-learn
  - scipy
  # optional
  - geopandas
  - matplotlib
  - numba
  - rtree
  - shapely
